[uwsgi]
wsgi-file = config/wsgi.py
stric = true # prevents the server from starting if it's misconfigured
socket = :8000
protocol = http
master = true # start a master process to manage child processes
no-orphans = true # terminate all child processes
die-on-term = true # stop the server upon receiving the SIGTERM signal
lazy-apps = true # this allows the server to start faster
processes = 4 # number of processes created by the master process
threads = 8 
enable-threads = true 
max-requests = 500
reload-on-rss = 1024
worker-reloadd-mercy = 60
harakiri = 60 
harakiri-verbose = true
vacuum = true
post-buffering = 1048576
buffer-size = 65535