services:
  db:
    image: postgres:16
    container_name: postgres
    ports:
      - "5432:5432" # NO exponer puertos 
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  django:
    build: 
      context: . 
      dockerfile: Dockerfile
    container_name: django_app
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./config/.env
    environment:
      - DB_HOST=db
      - DB_PORT=5432 # Agregar variables de entorno
    ports:
      - "8000:8000"

  nginx:
    image: nginx:1.25.3
    container_name: nginx_proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./configs:/etc/nginx/conf.d:ro
    depends_on:
      - django
    ports:
      - "8080:80"

volumes:
  postgres_data: